#公共配置
server:
  port: 8080
  servlet:
    context-path: /account
spring:
  application:
    name: account
  session:
    timeout: 1800
  mvc:
    view:
      prefix: /WEB-INF/pages
  devtools:
    restart:
      enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accountmanager?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        min-idle: 4
        max-idle: 8
    timeout: 30000
